#:kivy 2.1.0

#: import hex kivy.utils.get_color_from_hex


<PoetToggle>
    poet_name: ""
    poet_bio: ""

    orientation: "vertical"
    background_normal: "assets/img/toggle_off.png"
    background_down: "assets/img/toggle_on.png"
    padding: [72, 56, 72, 36]

    type_size: "20sp"

    Text:
        text: root.poet_name
        font_size: root.type_size
        text_size: self.size
        halign: "center"
